version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app
    environment:
      DB_HOST: db
      DB_DATABASE: news
      DB_USERNAME: ROOT
      DB_PASSWORD:
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  db:
    image: mysql:5.1.3
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'app-news'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER : 'root'
    networks:
      - app