const ActionTypes = Object.freeze({
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    LOAD_USER: 'LOAD_USER',
    AUTH_LOADING: 'AUTH_LOADING',
    LOADING_ALL_ARTICLES:'LOADING_ALL_ARTICLES',
    SEARCHING_ARTICLES:'SEARCHING_ARTICLES',
    SAVE_PREFERENCE:'SAVE_PREFERENCE',
    GET_PREFERENCE_BY_ID:'GET_PREFERENCE_BY_ID'


});
export default ActionTypes;